name: Daily Contribution Check

on:
  schedule:
    - cron: "50 23 * * *" # Runs every day at 11:50 PM UTC

jobs:
  check-contributions:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          - name: Check if secrets are set
          run: |
            if [ -z "$GITHUB_USERNAME" ]; then
              echo "GITHUB_USERNAME is not set"
              exit 1
            else
              echo "GITHUB_USERNAME is set"
            fi
            if [ -z "$REPO_NAME" ]; then
              echo "REPO_NAME is not set"
              exit 1
            else
              echo "REPO_NAME is set"
            fi
            if [ -z "$GITHUB_TOKEN" ]; then
              echo "GITHUB_TOKEN is not set"
              exit 1
            else
              echo "GITHUB_TOKEN is set"
            fi

      - name: Run contribution check script
        env:
          GITHUB_USERNAME: ${{ secrets.USERNAME }}
          REPO_NAME: ${{ secrets.REPO_NAME }}
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: |
          python main.py
