name: Daily Contribution Check

on:
  workflow_dispatch:
  schedule:
    - cron: "50 23 * * *" # Runs every day at 11:50 PM UTC

jobs:
  check-contributions:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Check if secrets are set
        run: |
          if [ -z "${{ secrets.USERNAME }}" ]; then
            echo "GITHUB_USERNAME is not set"
            exit 1
          else
            echo "GITHUB_USERNAME is set"
          fi
          if [ -z "${{ secrets.REPO_NAME }}" ]; then
            echo "REPO_NAME is not set"
            exit 1
          else
            echo "REPO_NAME is set"
          fi
          if [ -z "${{ secrets.ACCESS_TOKEN }}" ]; then
            echo "GITHUB_TOKEN is not set"
            exit 1
          else
            echo "GITHUB_TOKEN is set"
          fi

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run contribution check script
        env:
          USERNAME: ${{ secrets.USERNAME }}
          REPO_NAME: ${{ secrets.REPO_NAME }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: |
          python main.py
